---

- name: get yum repository
  get_url:
    url: https://packages.microsoft.com/config/rhel/{{ ansible_distribution_major_version }}/prod.repo
    dest: /etc/yum.repos.d/msprod.repo

- name: accept microsoft's eula and install mssql-tools
  yum:
    name:
      - mssql-tools
      - unixODBC-devel
    state: present
  environment:
    ACCEPT_EULA: "Y"

- name: add mssql-tools to path
  lineinfile:
    path: $HOME/.bashrc
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'

...
